mariadb: upgrade to 10.5.4
* Remove one backported patch
* Remove SRC_URI[md5sum]
* Rebase two patches to fix fuzz warnings
* Add curl depends to fix below error:
  | ./mariadb-10.5.4/storage/maria/libmarias3/libmarias3/marias3.h:26:10: fatal error: curl/curl.h: No such file or directory

* Fixes:
  | mv: cannot stat '/build/tmp/work/corei7-64-wrs-linux/mariadb/10.5.4-r0/image/lib/security': No such file or directory

* Disable rocksdb engine for arm64 to workaround undefined reference
  to `crc32c_arm64' as https://jira.mariadb.org/browse/MDEV-23137

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>